---
id: apache-arrow-tokyo
base_name: apache-arrow
tags:
- rabbit
- arrow
- data
presentation_date: 2017-06-13
version: 2017.6.13.2
licenses:
- CC-BY-SA-4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: 
  speaker_deck_user: 
